### ISSUE TITLE
Question about BBox annotation.

### ISSUE THREAD

**Issue by OuyangJunyuan** [tudelft-iv/view-of-delft-dataset#11]
![image](https://user-images.githubusercontent.com/37474760/176579097-c8a0abab-974f-43df-8b5d-c22c2f068050.png)
It seems to provide nothing about pitch and roll annotation, right?
I can only find the annotated yaw in these KITTI-like annoataion files.

**Comment by andraspalffy** [comment]
Hello, 

you are right, these angles are not there. This is because the official KITTI annotation format does not support pitch and roll angles, see  [here](https://github.com/bostondiditeam/kitti/blob/master/resources/devkit_object/readme.txt). In other words, we do not have a field to insert them. However, we do have them and plan to share them later.

**Comment by OuyangJunyuan** [comment]
> Hello,
> 
> you are right, these angles are not there. This is because the official KITTI annotation format does not support pitch and roll angles, see [here](https://github.com/bostondiditeam/kitti/blob/master/resources/devkit_object/readme.txt). In other words, we do not have a field to insert them. However, we do have them and plan to share them later.

Awesome! looking forward to the release of pitch and roll.
