### ISSUE TITLE
training data for the radar in actual dataset is not complete

### ISSUE THREAD

**Issue by shalinipatil2909** [tudelft-iv/view-of-delft-dataset#24]
I downloaded the dataset after receiving your mail. But the data in the radar folder is incomplete. image_2, label_2, pose folders are missing. and many files are of 1 or 2 kb only. please tell me how to proceed.

**Comment by andraspalffy** [comment]
The dataset **is** complete.

the files you are referring to are **symlinks**, pointing o the image_2, label_2, pose folders in the "lidar" parent folder.
This is by design, to reduce your download size, and to not duplicate data. Just think about it: the camera images do not change just because the point cloud files are replaced.

These work out of the box on Ubuntu. I guess you use Windows, on which we have never tried it. 

You can either:
- copy data from the "lidar" parent folder to the radar folder
- recreate symlinks with the Windows version
- or use Ubuntu.

Hope this helps.
