### ISSUE TITLE
Missing labels/pose files

### ISSUE THREAD

**Issue by MrTooOldDriver** [tudelft-iv/view-of-delft-dataset#4]
Hi, Thank you for making this great dataset! I have discovered some potential issues during exploration.

First looks like label files for seq 2532-3276 are missing
![image](https://user-images.githubusercontent.com/16554153/171354180-17338976-f535-41d5-a9a6-40e9ac091ba0.png)

Some pose files are empty/incomplete
00544.json is incomplete
![image](https://user-images.githubusercontent.com/16554153/171354234-060335f1-c38c-48b9-8bf7-77b962840317.png)

01312.json is empty
![image](https://user-images.githubusercontent.com/16554153/171354274-0755bd8e-1338-417b-a0b5-c4c0d30c0c77.png)

Thank you and hope this will helps. And please let me know if you would like me open as two issues. :D

**Comment by BalazsSzekeres** [comment]
Hi!

The labels for frames 2532-3276 are missing since they are the test set. The `ImageSets` folder in the set contains this information.

Where the information is missing, means that the information was not available for that given frame. We would suggest either interpolating that information or skipping those frames.

Hope this answers your questions!
