### ISSUE TITLE
About Coordinate Conversion

### ISSUE THREAD

**Issue by vehicle-jyw** [tudelft-iv/view-of-delft-dataset#46]
Hello, after using the method similar to PointPillars to convert a point cloud into BEV view, is the vehicle located on the far left with the front facing to the right? The image is a point cloud BEV feature map that I visualized based on the official PP
![image](https://github.com/tudelft-iv/view-of-delft-dataset/assets/108561792/146a0dde-eff9-41ed-9389-bfd54900fc44)

**Comment by andraspalffy** [comment]
Dear @vehicle-jyw, please understand that we cannot help with every detection algorithm step and bug you and others have because of time limitations. Also, here I do not know what code you used and what are the inputs, colors, and the axes.

That being said, it does seem like the car is on the left, facing to the right.
